### ISSUE TITLE
Update passport-oauth to ^1.0.0

### ISSUE THREAD

**Issue by analog-nico** [jeremybenaim/passport-500px#1]
Unless this library upgrades to passport-oauth ^1.0.0 it will crash `req.logIn(...)` when the app is using the latest version of Passport. This is caused by introducing lazy session initialization in passport 0.3.0. See [the technical details](https://github.com/jaredhanson/passport/pull/399) and [Jared's explanation](https://github.com/jaredhanson/passport/issues/400#issuecomment-135162085).

Let me know if I can help.

**Comment by analog-nico** [comment]
FYI, passport@0.3.1 just got released which applies a general patch. So I removed the "Critical" in the title.

**Comment by jeremybenaim** [comment]
Hey @analog-nico, thanks for raising this issue.

As you can see in the commits history this lib hasn't been updated for a long time, sorry about that!

I'll try to take a moment in the next couple of days to upgrade to the latest passport version and make sure everything works fine. Otherwise feel free to PR if you already fixed it on your side.

Thanks :)

**Comment by analog-nico** [comment]
I actually don't use this lib. I am just the messenger. ;) Anyway, the npm download stats show that you have quite a few users who would appreciate the update.

Bumping the version number and a quick authorization test should be enough.

**Comment by jeremybenaim** [comment]
All done, thanks again @analog-nico :)

**Comment by analog-nico** [comment]
Awesome, thank you!
